# This file specified which config should be loaded, based on the current branch.
#
# For example:
#
# - superbranch: super.rb
# - /dev/: dev.rb
# - /master/: master.rb
#
# The config file of the first match, from top to bottom, is loaded.

- /emu_cdm|c4c.staging/: common_c4c_staging.rb
- /moose_cdm|c4c.dev/: common_c4c_staging.rb
- /dev/: common_utopian_dev.rb
