# This file is copied from vendor/plugins/movement_tracker_canada/mappings.yml
#
# Make sure to edit that file, not the one in RAILS_ROOT/config/mappings.yml
#
lib_path: vendor/plugins/movement_tracker_canada/app/models

databases:
  <%= "intranet_#{RAILS_ENV}" %>: user, person, access, campus, school_year, year_in_school, campus, assignment, assignmentstatus, cim_hrdb_current_address, cim_hrdb_permanent_address, country, title, emerg, gender, region, state, cim_hrdb_admin, cim_hrdb_priv, cim_hrdb_staff, cim_hrdb_person_year, accountadmin_accessgroup, accountadmin_accountadminaccess, accountadmin_accesscategory, accountadmin_accountgroup, accountadmin_language, accountadmin_vieweraccessgroup, site_multilingual_label, month, prc, prcmethod, semester, semester_report, monthly_report, annual_report, annual_goals_report, week, weekly_report, year, staff
  <%= "pat_#{RAILS_ENV}" %>: pat/project, pat/profile, pat/appln, pat/form

tables:
  user: accountadmin_viewer
  person: cim_hrdb_person
  cim_hrdb_current_address: cim_hrdb_person
  cim_hrdb_permanent_address: cim_hrdb_person
  accountadmin_accessgroup: accountadmin_accessgroup
  accountadmin_accountadminaccess: accountadmin_accountadminaccess
  accountadmin_accesscategory: accountadmin_accesscategory
  accountadmin_accountgroup: accountadmin_accountgroup
  accountadmin_language: accountadmin_language
  accountadmin_vieweraccessgroup: accountadmin_vieweraccessgroup
  access: cim_hrdb_access
  campus: cim_hrdb_campus
  school_year: cim_hrdb_year_in_school
  year_in_school: cim_hrdb_year_in_school
  assignment: cim_hrdb_assignment
  assignmentstatus: cim_hrdb_assignmentstatus
  country: cim_hrdb_country
  title: cim_hrdb_title
  emerg: cim_hrdb_emerg
  gender: cim_hrdb_gender
  region: cim_hrdb_region
  state: cim_hrdb_province
  cim_hrdb_admin: cim_hrdb_admin
  cim_hrdb_priv: cim_hrdb_priv
  cim_hrdb_staff: cim_hrdb_staff
  cim_hrdb_person_year: cim_hrdb_person_year
  site_multilingual_label: site_multilingual_label
  month: cim_stats_month
  prc: cim_stats_prc
  prcmethod: cim_stats_prcmethod
  semester: cim_stats_semester
  semester_report: cim_stats_semesterreport
  week: cim_stats_week
  weekly_report: cim_stats_weeklyreport
  year: cim_stats_year
  monthly_report: cim_stats_monthlyreport
  annual_goals_report: cim_stats_annualgoalsreport
  annual_report: cim_stats_annualreport
  staff: cim_hrdb_staff

# ciministry
#year_in_school:
#  id: year_id
school_year:
  id: year_id
  name: year_desc
  level: year_id
year_in_school:
  id: year_id
  desc: year_desc
assignment:
  id: assignment_id
assignmentstatus:
  id: assignmentstatus_id
  desc: assignmentstatus_desc
country:
  id: country_id
  name: country_desc
  country: country_desc
  abbrev: country_shortDesc
  desc: country_desc
  short_desc: country_shortDesc
  iso_code: country_shortDesc
  code: country_shortDesc
emerg:
  id: emerg_id
gender:
  id: gender_id
  desc: gender_desc
region:
  id: region_id
  desc: reg_desc
state:
  id: province_id
  name: province_desc
  abbreviation: province_shortDesc
  abbrev: province_shortDesc
  
# Column Mappings
user:
  id: viewer_id
  last_login: viewer_lastLogin
  username: viewer_userID
  password: viewer_passWord
  is_active: viewer_isActive
  
person:
  id: person_id
  created_at: person_id
  first_name: person_fname
  last_name: person_lname
  middle_name: person_mname
  preferred_name: person_fname
  preferred_first_name: person_fname
  preferred_last_name: person_lname
  email: person_email
  address1: person_local_addr
  city: person_local_city
  zip: person_local_pc
  email: person_email

campus:
  id: campus_id
  name: campus_desc
  abbrv: campus_shortDesc
  state_id: province_id
  desc: campus_desc
  short_desc: campus_shortDesc
  short_name: campus_shortDesc
  
cim_hrdb_current_address:
  id: person_id
  address1: person_local_addr
  city: person_local_city
  zip: person_local_pc
  phone: person_local_phone
  email: person_email
  alternate_phone: cell_phone
  state_id: province_id
 
cim_hrdb_permanent_address:
  id: person_id
  address1: person_addr
  city: person_city
  zip: person_pc
  phone: person_phone
  email: person_email
  state_id: province_id
 
cim_hrdb_admin:
  id: admin_id

cim_hrdb_priv:
  id: priv_id
  accesslevel: priv_accesslevel
cim_hrdb_staff:
  id: staff_id
cim_hrdb_person_year:
  id: personyear_id

accountadmin_accessgroup:
  id: accessgroup_id
  key: accessgroup_key

accountadmin_accountadminaccess:
  id: accountadminaccess_id
  privilege: accountadminaccess_privilege

accountadmin_accesscategory:
  id: accesscategory_id
  key: accesscategory_key

accountadmin_accountgroup:
  id: accountgroup_id
  key: accountgroup_key
  label_long: accountgroup_label_long

accountadmin_language:
  id: language_id
  key: language_key
  code: language_code

accountadmin_vieweraccessgroup:
  id: vieweraccessgroup_id

access:
  id: access_id

site_multilingual_label:
  id: label_id
  key: label_key
  label: label_label
  moddate: label_moddate

year:
  id: year_id
  description: year_desc
  desc: year_desc

prc:
  id: prc_id
  first_name: prc_firstName
  method_id: prcMethod_id
  witness_name: prc_witnessName
  notes: prc_notes
  date: prc_date
  integrated_believer: prc_7upCompleted

prcmethod:
  id: prcMethod_id
  description: prcMethod_desc

semester:
  id: semester_id
  description: semester_desc
  desc: semester_desc
  start_date: semester_startDate

month:
  id: month_id
  description: month_desc
  desc: month_desc
  number: month_number
  calendar_year: month_calendaryear

weekly_report:
  id: weeklyReport_id
  spiritual_conversations: weeklyReport_1on1SpConv
  gospel_presentations: weeklyReport_1on1GosPres
  holyspirit_presentations: weeklyReport_1on1HsPres
  followup_completed: weeklyReport_7upCompleted
  spiritual_conversations_student: weeklyReport_1on1SpConvStd
  gospel_presentations_student: weeklyReport_1on1GosPresStd
  holyspirit_presentations_student: weeklyReport_1on1HsPresStd
  followup_completed_student: weeklyReport_7upCompletedStd
  cj_video: weeklyReport_cjVideo
  mda: weeklyReport_mda
  other_evmats: weeklyReport_otherEVMats
  rlk: weeklyReport_rlk
  siq: weeklyReport_siq
  notes: weeklyReport_notes

week:
  id: week_id
  end_date: week_endDate
  
semester_report:
  id: semesterreport_id
  average_hours_prayer: semesterreport_avgPrayer
  average_attendance_weekly_meetings: semesterreport_avgWklyMtg
  number_challenged_staff: semesterreport_numStaffChall
  number_challenged_internships: semesterreport_numInternChall
  number_frosh_involved: semesterreport_numFrosh
  number_staff_led_dg: semesterreport_numStaffDG
  number_in_staff_led_dg: semesterreport_numInStaffDG
  number_student_led_dg: semesterreport_numStudentDG
  number_in_student_led_dg: semesterreport_numInStudentDG
  number_sp_mult_in_staff_led_dg: semesterreport_numSpMultStaffDG
  number_sp_mult_in_student_led_dg: semesterreport_numSpMultStdDG
  total_graduating_students_to_non_ministry: semesterreport_totalSpMultGradNonMinistry
  total_graduating_students_to_full_time_c4c_staff: semesterreport_totalFullTimeC4cStaff
  total_graduating_students_to_full_time_p2c_non_c4c: semesterreport_totalFullTimeP2cStaffNonC4c
  total_graduating_students_to_one_year_internship: semesterreport_totalPeopleOneYearInternship
  total_graduating_students_to_other_ministry: semesterreport_totalPeopleOtherMinistry
  total_students_to_summit: semesterreport_studentsSummit
  total_students_to_wc: semesterreport_studentsWC
  total_students_to_project: semesterreport_studentsProjects
  
monthly_report:
  id: monthlyreport_id
  average_hours_prayer: monthlyreport_avgPrayer
  average_attendance_weekly_meetings: monthlyreport_avgWklyMtg
  number_frosh_involved: monthlyreport_numFrosh
  event_spiritual_conversations: monthlyreport_eventSpirConversations
  event_gospel_prensentations: monthlyreport_eventGospPres
  media_spiritual_conversations: monthlyreport_mediaSpirConversations
  media_gospel_prensentations: monthlyreport_mediaGospPres
  total_core_students: monthlyreport_totalCoreStudents
  total_students_in_dg: monthlyreport_totalStudentInDG
  total_spiritual_multipliers: monthlyreport_totalSpMult
  total_integrated_new_believers: montlyreport_integratedNewBelievers
  
annual_goals_report:
  id: annualGoalsReport_id
  students_in_ministry: annualGoalsReport_studInMin
  spiritual_multipliers: annualGoalsReport_sptMulti
  first_years:  annualGoalsReport_firstYears
  total_went_to_summit: annualGoalsReport_summitWent
  total_went_to_wc: annualGoalsReport_wcWent
  total_went_on_project: annualGoalsReport_projWent
  spiritual_conversations: annualGoalsReport_spConvTotal
  gospel_presentations: annualGoalsReport_gosPresTotal
  holyspirit_presentations: annualGoalsReport_hsPresTotal
  indicated_decisions: annualGoalsReport_prcTotal
  followup_completed: annualGoalsReport_integBelievers
  large_event_attendance: annualGoalsReport_lrgEventAttend 

annual_report:
  id: annualReport_id
    
staff:
  id: staff_id
