<%= 
dbh = "#{Rails.root}/config/database/database_header.yml"; dbhd = dbh+".default";
file = File.exists?(dbh) ? dbh : dbhd
File.read(file).chomp
%>

development:
  database: c4c_pulse_dev
  <<: *defaults

test:
  database: c4c_pulse_test
  <<: *defaults

production:
  database: c4c_pulse_dev
  <<: *defaults

ciministry_development:
  database: c4c_intranet_dev
  <<: *defaults

ciministry_production:
  database: c4c_intranet_dev
  <<: *defaults

ciministry_test:
  database: c4c_intranet_test
  <<: *defaults
